export interface Destination {
  city: string;
  country: string;
  emoji: string;
}

export const destinations: Destination[] = [
  // North America
  { city: "New York", country: "United States", emoji: "🇺🇸" },
  { city: "Los Angeles", country: "United States", emoji: "🇺🇸" },
  { city: "Miami", country: "United States", emoji: "🇺🇸" },
  { city: "Las Vegas", country: "United States", emoji: "🇺🇸" },
  { city: "San Francisco", country: "United States", emoji: "🇺🇸" },
  { city: "Chicago", country: "United States", emoji: "🇺🇸" },
  { city: "Nashville", country: "United States", emoji: "🇺🇸" },
  { city: "New Orleans", country: "United States", emoji: "🇺🇸" },
  { city: "Honolulu", country: "United States", emoji: "🇺🇸" },
  { city: "Austin", country: "United States", emoji: "🇺🇸" },
  { city: "Seattle", country: "United States", emoji: "🇺🇸" },
  { city: "Denver", country: "United States", emoji: "🇺🇸" },
  { city: "Scottsdale", country: "United States", emoji: "🇺🇸" },
  { city: "Savannah", country: "United States", emoji: "🇺🇸" },
  { city: "Charleston", country: "United States", emoji: "🇺🇸" },
  { city: "Portland", country: "United States", emoji: "🇺🇸" },
  { city: "San Diego", country: "United States", emoji: "🇺🇸" },
  { city: "Atlanta", country: "United States", emoji: "🇺🇸" },
  { city: "Dallas", country: "United States", emoji: "🇺🇸" },
  { city: "Houston", country: "United States", emoji: "🇺🇸" },
  { city: "Philadelphia", country: "United States", emoji: "🇺🇸" },
  { city: "Boston", country: "United States", emoji: "🇺🇸" },
  { city: "Washington D.C.", country: "United States", emoji: "🇺🇸" },
  { city: "Toronto", country: "Canada", emoji: "🇨🇦" },
  { city: "Vancouver", country: "Canada", emoji: "🇨🇦" },
  { city: "Montreal", country: "Canada", emoji: "🇨🇦" },
  { city: "Cancún", country: "Mexico", emoji: "🇲🇽" },
  { city: "Mexico City", country: "Mexico", emoji: "🇲🇽" },
  { city: "Tulum", country: "Mexico", emoji: "🇲🇽" },
  { city: "Playa del Carmen", country: "Mexico", emoji: "🇲🇽" },
  { city: "Cabo San Lucas", country: "Mexico", emoji: "🇲🇽" },
  { city: "Puerto Vallarta", country: "Mexico", emoji: "🇲🇽" },
  // Caribbean
  { city: "Nassau", country: "Bahamas", emoji: "🇧🇸" },
  { city: "Montego Bay", country: "Jamaica", emoji: "🇯🇲" },
  { city: "Kingston", country: "Jamaica", emoji: "🇯🇲" },
  { city: "Punta Cana", country: "Dominican Republic", emoji: "🇩🇴" },
  { city: "San Juan", country: "Puerto Rico", emoji: "🇵🇷" },
  { city: "Bridgetown", country: "Barbados", emoji: "🇧🇧" },
  { city: "Aruba", country: "Aruba", emoji: "🇦🇼" },
  { city: "St. Lucia", country: "Saint Lucia", emoji: "🇱🇨" },
  { city: "Havana", country: "Cuba", emoji: "🇨🇺" },
  { city: "Turks and Caicos", country: "Turks and Caicos", emoji: "🇹🇨" },
  { city: "St. Thomas", country: "US Virgin Islands", emoji: "🇻🇮" },
  { city: "Curaçao", country: "Curaçao", emoji: "🇨🇼" },
  { city: "Grand Cayman", country: "Cayman Islands", emoji: "🇰🇾" },
  { city: "Trinidad", country: "Trinidad and Tobago", emoji: "🇹🇹" },
  // Central & South America
  { city: "Bogotá", country: "Colombia", emoji: "🇨🇴" },
  { city: "Cartagena", country: "Colombia", emoji: "🇨🇴" },
  { city: "Medellín", country: "Colombia", emoji: "🇨🇴" },
  { city: "Lima", country: "Peru", emoji: "🇵🇪" },
  { city: "Cusco", country: "Peru", emoji: "🇵🇪" },
  { city: "Buenos Aires", country: "Argentina", emoji: "🇦🇷" },
  { city: "Rio de Janeiro", country: "Brazil", emoji: "🇧🇷" },
  { city: "São Paulo", country: "Brazil", emoji: "🇧🇷" },
  { city: "Santiago", country: "Chile", emoji: "🇨🇱" },
  { city: "San José", country: "Costa Rica", emoji: "🇨🇷" },
  { city: "Panama City", country: "Panama", emoji: "🇵🇦" },
  { city: "Quito", country: "Ecuador", emoji: "🇪🇨" },
  // Europe
  { city: "London", country: "United Kingdom", emoji: "🇬🇧" },
  { city: "Paris", country: "France", emoji: "🇫🇷" },
  { city: "Nice", country: "France", emoji: "🇫🇷" },
  { city: "Marseille", country: "France", emoji: "🇫🇷" },
  { city: "Rome", country: "Italy", emoji: "🇮🇹" },
  { city: "Milan", country: "Italy", emoji: "🇮🇹" },
  { city: "Florence", country: "Italy", emoji: "🇮🇹" },
  { city: "Venice", country: "Italy", emoji: "🇮🇹" },
  { city: "Amalfi Coast", country: "Italy", emoji: "🇮🇹" },
  { city: "Naples", country: "Italy", emoji: "🇮🇹" },
  { city: "Barcelona", country: "Spain", emoji: "🇪🇸" },
  { city: "Madrid", country: "Spain", emoji: "🇪🇸" },
  { city: "Ibiza", country: "Spain", emoji: "🇪🇸" },
  { city: "Seville", country: "Spain", emoji: "🇪🇸" },
  { city: "Mallorca", country: "Spain", emoji: "🇪🇸" },
  { city: "Marbella", country: "Spain", emoji: "🇪🇸" },
  { city: "Berlin", country: "Germany", emoji: "🇩🇪" },
  { city: "Munich", country: "Germany", emoji: "🇩🇪" },
  { city: "Amsterdam", country: "Netherlands", emoji: "🇳🇱" },
  { city: "Lisbon", country: "Portugal", emoji: "🇵🇹" },
  { city: "Porto", country: "Portugal", emoji: "🇵🇹" },
  { city: "Athens", country: "Greece", emoji: "🇬🇷" },
  { city: "Santorini", country: "Greece", emoji: "🇬🇷" },
  { city: "Mykonos", country: "Greece", emoji: "🇬🇷" },
  { city: "Crete", country: "Greece", emoji: "🇬🇷" },
  { city: "Prague", country: "Czech Republic", emoji: "🇨🇿" },
  { city: "Vienna", country: "Austria", emoji: "🇦🇹" },
  { city: "Zurich", country: "Switzerland", emoji: "🇨🇭" },
  { city: "Geneva", country: "Switzerland", emoji: "🇨🇭" },
  { city: "Dublin", country: "Ireland", emoji: "🇮🇪" },
  { city: "Edinburgh", country: "United Kingdom", emoji: "🇬🇧" },
  { city: "Copenhagen", country: "Denmark", emoji: "🇩🇰" },
  { city: "Stockholm", country: "Sweden", emoji: "🇸🇪" },
  { city: "Oslo", country: "Norway", emoji: "🇳🇴" },
  { city: "Helsinki", country: "Finland", emoji: "🇫🇮" },
  { city: "Reykjavik", country: "Iceland", emoji: "🇮🇸" },
  { city: "Budapest", country: "Hungary", emoji: "🇭🇺" },
  { city: "Warsaw", country: "Poland", emoji: "🇵🇱" },
  { city: "Krakow", country: "Poland", emoji: "🇵🇱" },
  { city: "Dubrovnik", country: "Croatia", emoji: "🇭🇷" },
  { city: "Split", country: "Croatia", emoji: "🇭🇷" },
  { city: "Istanbul", country: "Turkey", emoji: "🇹🇷" },
  { city: "Cappadocia", country: "Turkey", emoji: "🇹🇷" },
  { city: "Antalya", country: "Turkey", emoji: "🇹🇷" },
  { city: "Brussels", country: "Belgium", emoji: "🇧🇪" },
  { city: "Monaco", country: "Monaco", emoji: "🇲🇨" },
  { city: "Malta", country: "Malta", emoji: "🇲🇹" },
  { city: "Bucharest", country: "Romania", emoji: "🇷🇴" },
  { city: "Sofia", country: "Bulgaria", emoji: "🇧🇬" },
  { city: "Tallinn", country: "Estonia", emoji: "🇪🇪" },
  { city: "Riga", country: "Latvia", emoji: "🇱🇻" },
  // Africa
  { city: "Cape Town", country: "South Africa", emoji: "🇿🇦" },
  { city: "Johannesburg", country: "South Africa", emoji: "🇿🇦" },
  { city: "Marrakech", country: "Morocco", emoji: "🇲🇦" },
  { city: "Casablanca", country: "Morocco", emoji: "🇲🇦" },
  { city: "Cairo", country: "Egypt", emoji: "🇪🇬" },
  { city: "Nairobi", country: "Kenya", emoji: "🇰🇪" },
  { city: "Lagos", country: "Nigeria", emoji: "🇳🇬" },
  { city: "Accra", country: "Ghana", emoji: "🇬🇭" },
  { city: "Zanzibar", country: "Tanzania", emoji: "🇹🇿" },
  { city: "Mauritius", country: "Mauritius", emoji: "🇲🇺" },
  { city: "Seychelles", country: "Seychelles", emoji: "🇸🇨" },
  { city: "Dakar", country: "Senegal", emoji: "🇸🇳" },
  { city: "Addis Ababa", country: "Ethiopia", emoji: "🇪🇹" },
  { city: "Kigali", country: "Rwanda", emoji: "🇷🇼" },
  // Middle East
  { city: "Dubai", country: "United Arab Emirates", emoji: "🇦🇪" },
  { city: "Abu Dhabi", country: "United Arab Emirates", emoji: "🇦🇪" },
  { city: "Doha", country: "Qatar", emoji: "🇶🇦" },
  { city: "Tel Aviv", country: "Israel", emoji: "🇮🇱" },
  { city: "Amman", country: "Jordan", emoji: "🇯🇴" },
  { city: "Muscat", country: "Oman", emoji: "🇴🇲" },
  // Asia
  { city: "Tokyo", country: "Japan", emoji: "🇯🇵" },
  { city: "Kyoto", country: "Japan", emoji: "🇯🇵" },
  { city: "Osaka", country: "Japan", emoji: "🇯🇵" },
  { city: "Seoul", country: "South Korea", emoji: "🇰🇷" },
  { city: "Bangkok", country: "Thailand", emoji: "🇹🇭" },
  { city: "Phuket", country: "Thailand", emoji: "🇹🇭" },
  { city: "Chiang Mai", country: "Thailand", emoji: "🇹🇭" },
  { city: "Bali", country: "Indonesia", emoji: "🇮🇩" },
  { city: "Jakarta", country: "Indonesia", emoji: "🇮🇩" },
  { city: "Singapore", country: "Singapore", emoji: "🇸🇬" },
  { city: "Kuala Lumpur", country: "Malaysia", emoji: "🇲🇾" },
  { city: "Hong Kong", country: "Hong Kong", emoji: "🇭🇰" },
  { city: "Shanghai", country: "China", emoji: "🇨🇳" },
  { city: "Beijing", country: "China", emoji: "🇨🇳" },
  { city: "Taipei", country: "Taiwan", emoji: "🇹🇼" },
  { city: "Ho Chi Minh City", country: "Vietnam", emoji: "🇻🇳" },
  { city: "Hanoi", country: "Vietnam", emoji: "🇻🇳" },
  { city: "Manila", country: "Philippines", emoji: "🇵🇭" },
  { city: "Boracay", country: "Philippines", emoji: "🇵🇭" },
  { city: "Mumbai", country: "India", emoji: "🇮🇳" },
  { city: "Delhi", country: "India", emoji: "🇮🇳" },
  { city: "Goa", country: "India", emoji: "🇮🇳" },
  { city: "Jaipur", country: "India", emoji: "🇮🇳" },
  { city: "Colombo", country: "Sri Lanka", emoji: "🇱🇰" },
  { city: "Kathmandu", country: "Nepal", emoji: "🇳🇵" },
  { city: "Maldives", country: "Maldives", emoji: "🇲🇻" },
  // Oceania
  { city: "Sydney", country: "Australia", emoji: "🇦🇺" },
  { city: "Melbourne", country: "Australia", emoji: "🇦🇺" },
  { city: "Gold Coast", country: "Australia", emoji: "🇦🇺" },
  { city: "Auckland", country: "New Zealand", emoji: "🇳🇿" },
  { city: "Queenstown", country: "New Zealand", emoji: "🇳🇿" },
  { city: "Fiji", country: "Fiji", emoji: "🇫🇯" },
  { city: "Bora Bora", country: "French Polynesia", emoji: "🇵🇫" },
];
