project_id = "seruyblflufhgandrxsf"

[functions.replan-chat]
verify_jwt = false

[functions.lookup-user-by-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-trip-plan]
verify_jwt = false

[functions.save-trip-plan]
verify_jwt = false
